const firstname, lastname, age, dateofbirth, address;
name = 'lyn';
lastname ='fuster';
age ='41';
dateofbirth ='02/14/1977';
address ='S7N 1T1';
console.log('firstname: ', firstname);
console.log('lastname: ', lastName);
console.log('age: ', age );
console.log('dateofbirth: ', dateofbirth);
console.log('address: ', address);
